const CART_ITEM_BEGIN = "CART_ITEM_BEGIN";
const CART_ITEM_FAILURE = "CART_ITEM_FAILURE";
const CART_ITEM_SUCCESS_CART_ITEMS = "CART_ITEM_SUCCESS_CART_ITEMS";
const CART_ITEM_SUCCESS_CART_ITEM = "CART_ITEM_SUCCESS_CART_ITEM";

export const cartItemActions = {
  CART_ITEM_BEGIN,
  CART_ITEM_FAILURE,
  CART_ITEM_SUCCESS_CART_ITEMS,
  CART_ITEM_SUCCESS_CART_ITEM,
};
