const CATEGORY_BEGIN = "CATEGORY_BEGIN";
const CATEGORY_FAILURE = "CATEGORY_FAILURE";
const CATEGORY_SUCCESS_CATEGORIES = "CATEGORY_SUCCESS_CATEGORIES";
const CATEGORY_SUCCESS_CATEGORY = "CATEGORY_SUCCESS";

export const categoryActions = {
  CATEGORY_BEGIN,
  CATEGORY_FAILURE,
  CATEGORY_SUCCESS_CATEGORIES,
  CATEGORY_SUCCESS_CATEGORY,
};
