const ORDER_BEGIN = "ORDER_BEGIN";
const ORDER_FAILURE = "ORDER_FAILURE";
const ORDER_SUCCESS_ORDERS = "ORDER_SUCCESS_ORDERS";
const ORDER_SUCCESS_ORDER = "ORDER_SUCCESS";

export const orderActions = {
  ORDER_BEGIN,
  ORDER_FAILURE,
  ORDER_SUCCESS_ORDERS,
  ORDER_SUCCESS_ORDER,
};
