const PRODUCT_BEGIN = "PRODUCT_BEGIN";
const PRODUCT_FAILURE = "PRODUCT_FAILURE";
const PRODUCT_SUCCESS_PRODUCTS = "PRODUCT_SUCCESS_PRODUCTS";
const PRODUCT_SUCCESS_PRODUCT = "PRODUCT_SUCCESS_PRODUCT";

export const productActions = {
  PRODUCT_BEGIN,
  PRODUCT_FAILURE,
  PRODUCT_SUCCESS_PRODUCTS,
  PRODUCT_SUCCESS_PRODUCT,
};
