const USER_BEGIN = "USER_BEGIN";
const USER_FAILURE = "USER_FAILURE";
const USER_SUCCESS_USERS = "USER_SUCCESS_USERS";
const USER_SUCCESS_USER = "USER_SUCCESS";

export const userActions = { USER_BEGIN, USER_FAILURE, USER_SUCCESS_USERS, USER_SUCCESS_USER };
